INSERT INTO cards (name) VALUES ('belangstellend');
INSERT INTO cards (name) VALUES ('bescheiden');
INSERT INTO cards (name) VALUES ('betrouwbaar');
INSERT INTO cards (name) VALUES ('creatief');
INSERT INTO cards (name) VALUES ('doorzetter');
INSERT INTO cards (name) VALUES ('duidelijk');
INSERT INTO cards (name) VALUES ('eerlijk');
INSERT INTO cards (name) VALUES ('enthousiast');
INSERT INTO cards (name) VALUES ('flexibel');
INSERT INTO cards (name) VALUES ('geduldig');
INSERT INTO cards (name) VALUES ('genieter');
INSERT INTO cards (name) VALUES ('gevoelig');
INSERT INTO cards (name) VALUES ('gul');
INSERT INTO cards (name) VALUES ('humoristisch');
INSERT INTO cards (name) VALUES ('initiatiefrijk');
INSERT INTO cards (name) VALUES ('ijverig');
INSERT INTO cards (name) VALUES ('kan relativeren');
INSERT INTO cards (name) VALUES ('levendig');
INSERT INTO cards (name) VALUES ('makkelijke prater');
INSERT INTO cards (name) VALUES ('inlevingsvermogen');
INSERT INTO cards (name) VALUES ('mild');
INSERT INTO cards (name) VALUES ('moedig');
INSERT INTO cards (name) VALUES ('nuchter');
INSERT INTO cards (name) VALUES ('openhartig');
INSERT INTO cards (name) VALUES ('oplettend');
INSERT INTO cards (name) VALUES ('rustig');
INSERT INTO cards (name) VALUES ('serieus');
INSERT INTO cards (name) VALUES ('speels');
INSERT INTO cards (name) VALUES ('veelzijdig');
INSERT INTO cards (name) VALUES ('vedraagzaam');
INSERT INTO cards (name) VALUES ('vriendelijk');
INSERT INTO cards (name) VALUES ('vrolijk');
INSERT INTO cards (name) VALUES ('weet te overtuigen');
INSERT INTO cards (name) VALUES ('zelfverzekerd');
INSERT INTO cards (name) VALUES ('zorgzaam');
INSERT INTO cards (name) VALUES ('zorgvuldig');
