INSERT INTO cards (name) VALUES ('Ambitieus');
INSERT INTO cards (name) VALUES ('Avontuurlijk');
INSERT INTO cards (name) VALUES ('Behulpzaam');
INSERT INTO cards (name) VALUES ('Bemiddelaar');
INSERT INTO cards (name) VALUES ('Consequent');
INSERT INTO cards (name) VALUES ('Doelgericht');
INSERT INTO cards (name) VALUES ('Direct');
INSERT INTO cards (name) VALUES ('Evenwichtig');
INSERT INTO cards (name) VALUES ('Gedisciplineerd');
INSERT INTO cards (name) VALUES ('Gemoedelijk');
INSERT INTO cards (name) VALUES ('Handig');
INSERT INTO cards (name) VALUES ('Idealistisch');
INSERT INTO cards (name) VALUES ('Inspirerend');
INSERT INTO cards (name) VALUES ('Intelligent');
INSERT INTO cards (name) VALUES ('Krachtig');
INSERT INTO cards (name) VALUES ('Bedachtzaam');
INSERT INTO cards (name) VALUES ('Nieuwsgierig');
INSERT INTO cards (name) VALUES ('Ordelijk');
INSERT INTO cards (name) VALUES ('Organisator');
INSERT INTO cards (name) VALUES ('Praktisch');
INSERT INTO cards (name) VALUES ('Respectvol');
INSERT INTO cards (name) VALUES ('Kan goed luisteren');
INSERT INTO cards (name) VALUES ('Spontaan');
INSERT INTO cards (name) VALUES ('Tactvol');
INSERT INTO cards (name) VALUES ('Tevreden');
INSERT INTO cards (name) VALUES ('Toegewijd');
INSERT INTO cards (name) VALUES ('Vastberaden');
INSERT INTO cards (name) VALUES ('Verantwoordelijk');
INSERT INTO cards (name) VALUES ('Kan goed analyseren');
INSERT INTO cards (name) VALUES ('Voor jezelf opkomen');
INSERT INTO cards (name) VALUES ('Weet te onderscheiden');
INSERT INTO cards (name) VALUES ('Optimistisch');
INSERT INTO cards (name) VALUES ('Zelfstandig');
INSERT INTO cards (name) VALUES ('Ziet samenhang');
