INSERT INTO cards (name) VALUES ('ambiteus');
INSERT INTO cards (name) VALUES ('avontuurlijk');
INSERT INTO cards (name) VALUES ('behulpzaam');
INSERT INTO cards (name) VALUES ('bemiddelaar');
INSERT INTO cards (name) VALUES ('consequent');
INSERT INTO cards (name) VALUES ('doelgericht');
INSERT INTO cards (name) VALUES ('direct');
INSERT INTO cards (name) VALUES ('evenwichtig');
INSERT INTO cards (name) VALUES ('gedisciplineerd');
INSERT INTO cards (name) VALUES ('gemoedeljk');
INSERT INTO cards (name) VALUES ('handig');
INSERT INTO cards (name) VALUES ('idealistisch');
INSERT INTO cards (name) VALUES ('inspirerend');
INSERT INTO cards (name) VALUES ('intelligent');
INSERT INTO cards (name) VALUES ('krachtig');
INSERT INTO cards (name) VALUES ('bedachtzaam');
INSERT INTO cards (name) VALUES ('nieuwsgierig');
INSERT INTO cards (name) VALUES ('ordelijk');
INSERT INTO cards (name) VALUES ('organisator');
INSERT INTO cards (name) VALUES ('praktisch');
INSERT INTO cards (name) VALUES ('respectvol');
INSERT INTO cards (name) VALUES ('kan goed luisteren');
INSERT INTO cards (name) VALUES ('spontaan');
INSERT INTO cards (name) VALUES ('tactvol');
INSERT INTO cards (name) VALUES ('tevreden');
INSERT INTO cards (name) VALUES ('toegewijd');
INSERT INTO cards (name) VALUES ('vastberaden');
INSERT INTO cards (name) VALUES ('verantwoordelijk');
INSERT INTO cards (name) VALUES ('kan goed analyseren');
INSERT INTO cards (name) VALUES ('voor jezelf opkomen');
INSERT INTO cards (name) VALUES ('weet te ondescheiden');
INSERT INTO cards (name) VALUES ('optimistisch');
INSERT INTO cards (name) VALUES ('zelfstandig');
INSERT INTO cards (name) VALUES ('ziet samenhang');
