INSERT INTO cards (name) VALUES ('Belangstellend');
INSERT INTO cards (name) VALUES ('Bescheiden');
INSERT INTO cards (name) VALUES ('Betrouwbaar');
INSERT INTO cards (name) VALUES ('Creatief');
INSERT INTO cards (name) VALUES ('Doorzetter');
INSERT INTO cards (name) VALUES ('Duidelijk');
INSERT INTO cards (name) VALUES ('Eerlijk');
INSERT INTO cards (name) VALUES ('Enthousiast');
INSERT INTO cards (name) VALUES ('Flexibel');
INSERT INTO cards (name) VALUES ('Geduldig');
INSERT INTO cards (name) VALUES ('Genieter');
INSERT INTO cards (name) VALUES ('Gevoelig');
INSERT INTO cards (name) VALUES ('Gul');
INSERT INTO cards (name) VALUES ('Humoristisch');
INSERT INTO cards (name) VALUES ('Initiatiefrijk');
INSERT INTO cards (name) VALUES ('Ijverig');
INSERT INTO cards (name) VALUES ('Kan relativeren');
INSERT INTO cards (name) VALUES ('Levendig');
INSERT INTO cards (name) VALUES ('Makkelijke prater');
INSERT INTO cards (name) VALUES ('Inlevingsvermogen');
INSERT INTO cards (name) VALUES ('Mild');
INSERT INTO cards (name) VALUES ('Moedig');
INSERT INTO cards (name) VALUES ('Nuchter');
INSERT INTO cards (name) VALUES ('Openhartig');
INSERT INTO cards (name) VALUES ('Oplettend');
INSERT INTO cards (name) VALUES ('Rustig');
INSERT INTO cards (name) VALUES ('Serieus');
INSERT INTO cards (name) VALUES ('Speels');
INSERT INTO cards (name) VALUES ('Veelzijdig');
INSERT INTO cards (name) VALUES ('Verdraagzaam');
INSERT INTO cards (name) VALUES ('Vriendelijk');
INSERT INTO cards (name) VALUES ('Vrolijk');
INSERT INTO cards (name) VALUES ('Weet te overtuigen');
INSERT INTO cards (name) VALUES ('Zelfverzekerd');
INSERT INTO cards (name) VALUES ('Zorgzaam');
INSERT INTO cards (name) VALUES ('Zorgvuldig');
